### ISSUE TITLE
strongly typed query responses

### ISSUE THREAD

**Issue by nkostis** [InfluxCommunity/influxdb3-csharp#49]
### Use Case

hi is there a plan to support strongly typed response objects to influx queries?

### Expected behavior

we'd expect responses to be similar to influx v2 and v1 drivers, where timestamps, tags and fields are clearly defined and shown and can easily be understood and manipulated.

### Actual behavior

Currently the responses are ienumerable of `object[]`:
```
public async IAsyncEnumerable<object?[]> Query(string query, QueryType? queryType = null, string? database = null)
```

**Comment by bednar** [comment]
Hi @nkostis,

we are currently works https://github.com/InfluxCommunity/influxdb3-csharp/pull/40. For more info see:

https://github.com/InfluxCommunity/influxdb3-csharp/pull/40/files#diff-ea62c7ee5ca92cf51704098db673cf40af3b3463324d7c86f7b25556a44f76e8

Best
