### ISSUE TITLE
[influxdb3-csharp]Does this support read Organization list and create Organization?

### ISSUE THREAD

**Issue by Shirley-Ji-59** [InfluxCommunity/influxdb3-csharp#87]
### Use Case

Hi, I am new here for influxdb 3.0, and I want to know whether this library support read Organization list and create it?

### Expected behavior

support read Organization list and create it

### Actual behavior

maybe does not support it.

**Comment by bednar** [comment]
Hi @Shirley-Ji-59,

Thank you for using InfluxDB 3 and for your interest in this client. I appreciate your engagement and the opportunity to clarify the scope of the client's functionality.

Currently, the primary focus of this client is to facilitate querying and writing operations within InfluxDB 3. As such, features related to the management API are not implemented in this version of the client. Moreover, adding support for management API functionalities is not on our roadmap.

We understand that management capabilities can be crucial for certain applications, and we're always evaluating ways to enhance our client based on user feedback. While these features are not available at the moment, we welcome any PR to review and merge.

Thank you again for your support and understanding.

Best Regards.
